export const ADDACTION="ADDACTION";
export const REMOVEACTION="REMOVEACTION";
export const ADDCLICKACTION="ADDCLICKACTION";
export const REMOVECLICKACTION="REMOVECLICKACTION";
export const SETREPEATMODE="SETREPEATMODE";